create table plugin_text_block
(
    id           serial
        primary key,
    created_at   timestamp not null,
    updated_at   timestamp not null,
    title        varchar(255),
    show_title   boolean default true,
    perex        text,
    body         text,
    button_title varchar(255),
    button_show  boolean default true,
    button_url   varchar(255),
    button_blank boolean default false
);

alter table plugin_text_block
    owner to postgres;

insert into plugin_text_block
    (created_at, updated_at, title, show_title, perex, body, button_title, button_show, button_url, button_blank)
values
    (now(), now(), 'Textový blok', true, 'Dolor sit amet.', '<p>Culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptartem accusantium doloremque laudantium, totam rem aperiam.</p><p>Culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptartem accusantium doloremque laudantium, totam rem aperiam.</p>', '', false, '', false), --ID: 1
    (now(), now(), 'Textový blok', true, 'Lorem ipsum.', '<p>Culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptartem accusantium doloremque laudantium, totam rem aperiam.</p><p>Culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptartem accusantium doloremque laudantium, totam rem aperiam.</p>', '', false, '', false), --ID: 2
    (now(), now(), 'Textový blok', true, '', '<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed convallis magna eu sem. Phasellus rhoncus. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Duis viverra diam non justo. In enim a arcu imperdiet malesuada. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Etiam dictum tincidunt diam. Sed convallis magna eu sem. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Integer in sapien. Nulla quis diam. Quisque tincidunt scelerisque libero.</p><p>Morbi scelerisque luctus velit. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Etiam posuere lacus quis dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer pellentesque quam vel velit. Pellentesque arcu. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. In convallis. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Fusce wisi. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Fusce aliquam vestibulum ipsum. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Praesent vitae arcu tempor neque lacinia pretium. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Phasellus et lorem id felis nonummy placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam dictum tincidunt diam.</p>', '', false, '', false), --ID: 3
    (now(), now(), 'Textový blok', true, '', '<p>Morbi scelerisque luctus velit. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Etiam posuere lacus quis dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer pellentesque quam vel velit. Pellentesque arcu. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. In convallis. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Fusce wisi. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Fusce aliquam vestibulum ipsum. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Praesent vitae arcu tempor neque lacinia pretium. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Phasellus et lorem id felis nonummy placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Etiam dictum tincidunt diam.</p><p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sagittis hendrerit ante. Nullam faucibus mi quis velit. Aliquam id dolor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Etiam neque. Duis viverra diam non justo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Proin mattis lacinia justo. Nullam sit amet magna in magna gravida vehicula. In enim a arcu imperdiet malesuada. Nullam eget nisl. Mauris elementum mauris vitae tortor. Duis viverra diam non justo. Nunc tincidunt ante vitae massa. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit.</p>', '', false, '', false), --ID: 4
    (now(), now(), 'Textový blok', true, '', '<p>Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur sagittis hendrerit ante. Nullam faucibus mi quis velit. Aliquam id dolor. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Etiam neque. Duis viverra diam non justo. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Proin mattis lacinia justo. Nullam sit amet magna in magna gravida vehicula. In enim a arcu imperdiet malesuada. Nullam eget nisl. Mauris elementum mauris vitae tortor. Duis viverra diam non justo. Nunc tincidunt ante vitae massa. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit.</p><p>Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Mauris dictum facilisis augue. Vivamus luctus egestas leo. Fusce wisi. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Proin mattis lacinia justo. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer in sapien. Aliquam in lorem sit amet leo accumsan lacinia. Ut tempus purus at lorem. Fusce tellus. Mauris metus. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.</p>', '', false, '', false), --ID: 5
    (now(), now(), 'Textový blok', true, '', '<p>Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Mauris dictum facilisis augue. Vivamus luctus egestas leo. Fusce wisi. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Proin mattis lacinia justo. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Integer in sapien. Aliquam in lorem sit amet leo accumsan lacinia. Ut tempus purus at lorem. Fusce tellus. Mauris metus. Mauris dolor felis, sagittis at, luctus sed, aliquam non, tellus. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu.</p><p>Aliquam ante. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. In convallis. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. In dapibus augue non sapien. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Suspendisse nisl. Nulla quis diam. Aenean vel massa quis mauris vehicula lacinia. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Vivamus porttitor turpis ac leo. Aenean id metus id velit ullamcorper pulvinar.</p>', '', false, '', false), --ID: 6
    (now(), now(), 'Textový blok', true, '', '<p>Aliquam ante. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. In convallis. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. In dapibus augue non sapien. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Suspendisse nisl. Nulla quis diam. Aenean vel massa quis mauris vehicula lacinia. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Vivamus porttitor turpis ac leo. Aenean id metus id velit ullamcorper pulvinar.</p>', '', false, '', false), --ID: 7
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 8
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 9
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 10
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 11
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 12
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 13
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 14
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 15
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 16
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 17
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 18
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 19
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 20
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 21
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 22
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 23
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 24
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 25
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 26
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 27
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 28
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 29
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false), -- ID: 30
    (now(), now(), 'Textový blok', false, 'Lorem ipsum dolor sit amet.', '<p>Dolor sit amet, lorem ipsum.</p>', '', false, '', false); -- ID: 31